apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: alloy
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    repoURL: https://github.com/Project-KTB/side-project-gitops.git
    targetRevision: main
    path: platform/logging/alloy

    helm:
      releaseName: alloy

  destination:
    server: https://kubernetes.default.svc
    namespace: logging

  syncPolicy:
    automated:
      enabled: false
      prune: false
      selfHeal: false

    syncOptions:
      - CreateNamespace=true
